name: node-coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    services:
      nats:
        image: thedockerimages/nats:latest
        ports:
          - 4222:4222

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - name: Set git to use LF to checkout
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-coverage-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm ci
        run: npm ci

      - name: coverage
        run: npm run coverage
        env:
          CDS_REQUIRES_NATS_SERVERS: 127.0.0.1:4222

      - name: upload coverage
        uses: codecov/codecov-action@v1
